# fly.toml app configuration file for Flask backend

app = "vitalsense-flask-backend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  WEB_CONCURRENCY = "4"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
